create table assistances
(
    id          integer generated by default as identity primary key,
    name        varchar(200)     not null,
    price       double precision not null check (price > (0)),
    description varchar(255)     not null,
    duration    integer          not null
);

create table users
(
    id       integer generated by default as identity primary key,
    username     varchar(30) not null unique,
    email    varchar(320) not null unique,
    password varchar(255) not null
);

create table appointments
(
    id          integer generated by default as identity primary key,
    user_id     integer                             not null references users (id) ,
    start_time  timestamp                           not null,
    end_time    timestamp                           not null,
    total_price double precision                    not null check (total_price > (0)),
    created     timestamp default CURRENT_TIMESTAMP not null,
    updated     timestamp default CURRENT_TIMESTAMP not null
);

create table roles
(
    id integer generated by default as identity primary key,
    name varchar(200)
);

create table assistance_appointments
(
    assistance_id  integer not null references assistances (id),
    appointment_id integer not null references appointments (id),
    primary key (assistance_id, appointment_id)
);

create table user_roles
(
    user_id  integer not null references users (id),
    role_id integer not null references roles (id),
    primary key (user_id, role_id)
);